export const firms = [
  "Krankenhaus Essen",
  "Polizei Saarland",
  "TTW",
  "Juwwi Inc.",
  "Damenstrümpfe Shop",
  "Hundesportverein",
  "C13",
  "Klaus Jakob",
  "Brauerei Ems",
  "Kirche Köln",
  "Blutspende e.V.",
  "Stadt Tübungen",
  "Stadt Blankenburg",
  "Feuerwehr Ötzingen",
  "StackOverflow",
  "Filmstudio Baden",
  "Fotostudio Rütger",
  "Autobauer Süd",
  "Schützenverein Siegburg",
  "Konditorei Wien",
  "Schnitzelhaus - Armes Schwein(vegan)",
  "Schuhputzer vom Bahnhof",
  "Kirchlicher Gangsterrap e.V",
  "Fleischerei Dahmer",
  "Kopenhagener Werft",
  "Schweizer Marine",
];

export const officeData = [
  {
    office1: {
      officeImageUrl: "./assets/office/1.jpg",
      titel: "Büro: Straßenverkäufer",
      imageTitle: "Auf der Straße",
      beschreibung:
        "Ohne Dach über dem Kopf startest du dein Unternehmen mit den einfachsten Mitteln",
      preis: 2000,
      incomemultiplikator: 1.2,
      nextOffice: "office2",
    },
  },
  {
    office2: {
      officeImageUrl: "./assets/office/2.jpg",
      titel: "Büro: Unter der Brücke",
      imageTitle: "Unter der Brücke",
      beschreibung:
        "Immerhin wirst du und dein Equipment nicht nass. Du kannst hier die ersten Meetings starten.",
      preis: 5000,
      incomemultiplikator: 1.5,
      nextOffice: "office3",
    },
  },
  {
    office3: {
      officeImageUrl: "./assets/office/3.jpg",
      titel: "Büro: Fast Food Restaurant",
      imageTitle: "Restaurant",
      beschreibung:
        "Deine ersten Einnahmen Sorgen für Kaffee und die Nutzung eines öffentlichen Internetanschlusses",
      preis: 10000,
      incomemultiplikator: 1.5,
      nextOffice: "office4",
    },
  },
  {
    office4: {
      officeImageUrl: "./assets/office/4.jpg",
      titel: "Büro: Homeoffice",
      imageTitle: "Homeoffice",
      beschreibung:
        "Warum bist du da nicht früher drauf gekommen? Einfach von zu Hause arbeiten",
      preis: 16000,
      incomemultiplikator: 1.5,
      nextOffice: "office5",
    },
  },
  {
    office5: {
      officeImageUrl: "./assets/office/5.jpg",
      titel: "Büro: Kleines Büro",
      imageTitle: "Kleines Büro",
      beschreibung: "Deine erste kleine Firmenzentrale. Glückwunsch!",
      preis: 25000,
      incomemultiplikator: 1.5,
      nextOffice: "office6",
    },
  },
  {
    office6: {
      officeImageUrl: "./assets/office/6.jpg",
      titel: "Büro: Mittleres Büro",
      imageTitle: "Mittleres Büro",
      beschreibung:
        "Jetzt verhandeln auch die Großen mit dir. Und es gibt Pizza und Kuchen für alle!",
      preis: 75000,
      incomemultiplikator: 1.5,
      nextOffice: "office7",
    },
  },
  {
    office7: {
      officeImageUrl: "./assets/office/7.webp",
      titel: "Büro: Wolkenkratzer",
      imageTitle: "Skyline",
      beschreibung:
        "Du hast es geschafft!!! Deine Firma ist das wichtigste Unternehmen weltweit!!! The Sky is the limit!",
      incomemultiplikator: 1.5,
      nextOffice: "office7",
    },
  },
];

export const workerImg = [
  {
    workerImageUrl: "./assets/worker/Hassan.png",
    name: "Hassan",
    active: true,
    hidden: false,
    cost: 0,
    description: "Mag Weihnachten",
    upgradelist: {
      upgrade1: {
        name: "Studium der Ökonomie",
        beschreibung: "Schnellere Auftragssuche per Klick",
        upgr: "upgr1",
        upgrcost: 1000,
        kindClickFindWork: true,
        multiplierkindClickFindWork: 2,
      },
      upgrade2: {
        name: "Charme-Offensive",
        beschreibung: "Erhöht Einnahmen pro Auftrag",
        upgr: "upgr2",
        upgrcost: 8000,
        kindIncomeperOrder: true,
        multiplierIncomeperOrder: 2,
      },
      upgrade3: {
        name: "Ritt auf der Cash Cow",
        beschreibung: "Beschleunigt die automatische Suche",
        upgr: "upgr3",
        upgrcost: 20000,
        kindFasterSearchOrders: true,
        multiplierkindFasterSearchOrders: 1,
      },
      upgrade4: {
        name: "Als Weihnachtsmann verkleiden",
        beschreibung: "Verbessert alle Werte",
        upgr: "upgr4",
        upgrcost: 50000,
        kindFasterSearchOrders: true,
        multiplierkindFasterSearchOrders: 5,
        kindIncomeperOrder: true,
        multiplierIncomeperOrder: 2,
        kindClickWork: true,
        multiplierkindClickWork: 5,
        kindClickFindWork: true,
        multiplierkindClickFindWork: 5,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
    },
  },
  {
    workerImageUrl: "./assets/worker/Marius.png",
    name: "Marius",
    active: true,
    hidden: false,
    cost: 0,
    description: "Coding Mastermind",
    upgradelist: {
      upgrade1: {
        name: "Geheimer Fußball-Algorithmus",
        beschreibung: "Programmiert schneller per Klick",
        upgr: "upgr5",
        upgrcost: 2000,
        kindClickWork: true,
        multiplierkindClickWork: 2,
      },
      upgrade2: {
        name: "Hält legendärs Weekly",
        beschreibung: "Schnellere automatische Programmierung",
        upgr: "upgr6",
        upgrcost: 10000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 1,
      },
      upgrade3: {
        name: "Fährt zur Messe",
        beschreibung: "Beschleunigt die automatische Suche",
        upgr: "upgr7",
        upgrcost: 20000,
        kindFasterSearchOrders: true,
        multiplierkindFasterSearchOrders: 2,
      },
      upgrade4: {
        name: "Geht zum Friseur",
        beschreibung: "Verbessert alle Werte",
        upgr: "upgr8",
        upgrcost: 60000,
        kindFasterSearchOrders: true,
        multiplierkindFasterSearchOrders: 3,
        kindIncomeperOrder: true,
        multiplierIncomeperOrder: 2,
        kindClickWork: true,
        multiplierkindClickWork: 5,
        kindClickFindWork: true,
        multiplierkindClickFindWork: 5,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
    },
  },
  {
    workerImageUrl: "./assets/worker/Katharina.png",
    name: "Katharina",
    soundUrl: "./assets/sounds/howdareyou.mp3",
    active: false,
    hidden: false,
    extra: "startSearch",
    cost: 300,
    description: "Hält alles zusammen",
    firebutton: true,
    upgradelist: {
      upgrade1: {
        name: "Befreit sich von starren Konzernen",
        beschreibung: "Schnellere automatische Auftragssuche",
        upgr: "upgr9",
        upgrcost: 1000,
        kindFasterSearchOrders: true,
        multiplierkindFasterSearchOrders: 4,
      },
      upgrade2: {
        name: "Hilfeboost für die GF",
        beschreibung: "Schnellere automatische Auftragssuche",
        upgr: "upgr10",
        upgrcost: 10000,
        kindFasterSearchOrders: true,
        multiplierkindFasterSearchOrders: 4,
      },
      upgrade3: {
        name: "KUCHEN!!!",
        beschreibung: "Verbessert alle Werte",
        upgr: "upgr11",
        upgrcost: 65000,
        kindFasterSearchOrders: true,
        multiplierkindFasterSearchOrders: 3,
        kindIncomeperOrder: true,
        multiplierIncomeperOrder: 2,
        kindClickWork: true,
        multiplierkindClickWork: 5,
        kindClickFindWork: true,
        multiplierkindClickFindWork: 5,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
    },
  },
  {
    workerImageUrl: "./assets/worker/Nathaniel.png",
    name: "Nathaniel",
    soundUrl: "./assets/sounds/ehernicht.mp3",
    active: false,
    hidden: false,
    extra: "startDevelop",
    cost: 1000,
    description: "Gibt useState eine neue Bedeutung",
    upgradelist: {
      upgrade1: {
        name: "Kommt später zur Weihnachtsfeier",
        beschreibung: "Programmiert schneller",
        upgr: "upgr12",
        upgrcost: 1000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
      upgrade2: {
        name: "Geht früher von der Weihnachtsfeier",
        beschreibung: "Programmiert schneller",
        upgr: "upgr13",
        upgrcost: 10000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
      upgrade3: {
        name: "Tanzt den Beamtenboogie",
        beschreibung: "Programmiert schneller",
        upgr: "upgr14",
        upgrcost: 65000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
    },
  },
  {
    workerImageUrl: "./assets/worker/Franz.png",
    name: "Franz",
    soundUrl: "./assets/sounds/worangelegen.mp3",
    active: false,
    hidden: false,
    cost: 3000,
    description: "Schwebt wie ein Schmetterling, programmiert wie eine Biene",
    upgradelist: {
      upgrade1: {
        name: "Koffein-Boost",
        beschreibung: "Programmiert schneller",
        upgr: "upgr15",
        upgrcost: 1000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 1,
      },
      upgrade2: {
        name: "Zeigt den Autobauern was wirklich schnell ist",
        beschreibung: "Programmiert schneller",
        upgr: "upgr16",
        upgrcost: 10000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 3,
      },
      upgrade3: {
        name: "Zieht die Cap verkehrt herum auf",
        beschreibung: "Programmiert schneller",
        upgr: "upgr17",
        upgrcost: 65000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
    },
  },
  {
    workerImageUrl: "./assets/worker/Dave.png",
    name: "Dave",
    soundUrl: "./assets/sounds/haltstop.mp3",
    active: false,
    hidden: false,
    cost: 5000,
    description: "Im Bruderkampf",
    upgradelist: {
      upgrade1: {
        name: "1on1 gegen den Drucker",
        beschreibung: "Schnellere automatische Auftragssuche",
        upgr: "upgr16",
        upgrcost: 1000,
        multiplierkindFasterSearchOrders: 5,
        kindIncomeperOrder: true,
      },
      upgrade2: {
        name: "Hält legendärs Weekly",
        beschreibung: "Schnellere automatische Programmierung",
        upgr: "upgr6",
        upgrcost: 10000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 1,
      },
      upgrade3: {
        name: "Kommt persönlich ins Büro!",
        beschreibung: "Alle arbeiten schneller",
        upgr: "upgr7",
        upgrcost: 65000,
        kindFasterSearchOrders: true,
        multiplierkindFasterSearchOrders: 3,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
    },
  },
  {
    workerImageUrl: "./assets/worker/Romeo.png",
    name: "Romeo",
    soundUrl: "./assets/sounds/neee.mp3",
    active: false,
    hidden: false,
    cost: 8000,
    description: "'Könnt ihr mich hören?'",
    upgradelist: {
      upgrade1: {
        name: "Arbeitet vom Auto aus",
        beschreibung: "Programmiert schneller",
        upgr: "upgr21",
        upgrcost: 1000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
      upgrade2: {
        name: "Zeigt dem Neuen wie der Laden läuft",
        beschreibung: "Programmiert schneller",
        upgr: "upgr22",
        upgrcost: 10000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 3,
      },
      upgrade3: {
        name: "Nimmt Nachhilfe bei Dave",
        beschreibung: "Programmiert schneller",
        upgr: "upgr23",
        upgrcost: 65000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
    },
  },
  {
    workerImageUrl: "./assets/worker/Mike.png",
    name: "Mike",
    soundUrl: "./assets/sounds/jaaberauchnein.mp3",
    active: false,
    hidden: false,
    cost: 10000,
    description: "Zockerkönig",
    upgradelist: {
      upgrade1: {
        name: "Findet bei Escape from Tarkov eine Grafikkarte",
        beschreibung: "Programmiert schneller",
        upgr: "upgr24",
        upgrcost: 1000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
      upgrade2: {
        name: "Findet in Cyberpunk ikonische Waffen",
        beschreibung: "Programmiert schneller",
        upgr: "upgr25",
        upgrcost: 65000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 3,
      },
      upgrade3: {
        name: "Spielt mit allen eine Runde CS",
        beschreibung: "Programmiert schneller",
        upgr: "upgr26",
        upgrcost: 65000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
    },
  },
  {
    workerImageUrl: "./assets/worker/Cornelius.png",
    name: "Cornelius",
    soundUrl: "./assets/sounds/nogod.mp3",
    active: false,
    hidden: false,
    cost: 14000,
    description: "Raketenmann",
    upgradelist: {
      upgrade1: {
        name: "Macht Homemade-Pasta",
        beschreibung: "Programmiert schneller",
        upgr: "upgr27",
        upgrcost: 1000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
      upgrade2: {
        name: "Baut sich einen neuen Arbeitstisch",
        beschreibung: "Programmiert schneller",
        upgr: "upgr6",
        upgrcost: 10000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 3,
      },
      upgrade3: {
        name: "Lernt versehentlich 4 neue Programmiersprachen",
        beschreibung: "Programmiert schneller",
        upgr: "upgr29",
        upgrcost: 65000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
    },
  },
  {
    workerImageUrl: "./assets/worker/Nadia.png",
    name: "Nadia",
    soundUrl: "./assets/sounds/fatal.mp3",
    active: false,
    hidden: false,
    cost: 18000,
    description: "Coding Judan",
    upgradelist: {
      upgrade1: {
        name: "Entwickelt App für 4 Screens",
        beschreibung: "Programmiert schneller",
        upgr: "upgr30",
        upgrcost: 1000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
      upgrade2: {
        name: "Isst etwas beim Meeting aus einer Schüssel",
        beschreibung: "Programmiert schneller",
        upgr: "upgr31",
        upgrcost: 10000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 3,
      },
      upgrade3: {
        name: "Rettet Christopher (mal wieder) den Tag",
        beschreibung: "Programmiert schneller",
        upgr: "upgr7",
        upgrcost: 65000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
    },
  },
  {
    workerImageUrl: "./assets/worker/Tony.png",
    name: "Tony",
    soundUrl: "./assets/sounds/computernein.mp3",
    active: false,
    hidden: false,
    cost: 22000,
    description: "Influencer",
    upgradelist: {
      upgrade1: {
        name: "Spielt eine Runde NES!",
        beschreibung: "Programmiert schneller",
        upgr: "upgr33",
        upgrcost: 1000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
      upgrade2: {
        name: "Spielt eine Runde SNES!!",
        beschreibung: "Programmiert schneller",
        upgr: "upgr34",
        upgrcost: 10000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 3,
      },
      upgrade3: {
        name: "Spielt eine Runde N64!!!",
        beschreibung: "Programmiert schneller",
        upgr: "upgr35",
        upgrcost: 65000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
    },
  },
  {
    workerImageUrl: "./assets/worker/Christopher.png",
    name: "Christopher",
    soundUrl: "./assets/sounds/ok.mp3",
    active: false,
    hidden: false,
    cost: 30000,
    description: "Auf Jobsuche",
    upgradelist: {
      upgrade1: {
        name: "Hält Nadia vom Arbeiten ab",
        beschreibung: "Programmiert schneller",
        upgr: "upgr36",
        upgrcost: 1000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
      upgrade2: {
        name: "Hält Katharina vom Arbeiten ab",
        beschreibung: "Programmiert schneller",
        upgr: "upgr37",
        upgrcost: 10000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 3,
      },
      upgrade3: {
        name: "Bastelt ein Spiel und hälte alle vom Arbeiten ab",
        beschreibung: "Programmiert schneller",
        upgr: "upgr38",
        upgrcost: 65000,
        kindWorkFaster: true,
        multiplierkindWorkFaster: 2,
      },
    },
  },
  {
    workerImageUrl: "./assets/worker/who.png",
    name: "Who",
    hidden: true,
  },
];
